package com.laguantera.dao;
// Generated 21-dic-2010 23:39:28 by Hibernate Tools 3.2.1.GA



/**
 * CostesDerivadosId generated by hbm2java
 */
public class CostesDerivadosId  implements java.io.Serializable {


     private int idTipoCoste;
     private int idVehiculo;

    public CostesDerivadosId() {
    }

    public CostesDerivadosId(int idTipoCoste, int idVehiculo) {
       this.idTipoCoste = idTipoCoste;
       this.idVehiculo = idVehiculo;
    }
   
    public int getIdTipoCoste() {
        return this.idTipoCoste;
    }
    
    public void setIdTipoCoste(int idTipoCoste) {
        this.idTipoCoste = idTipoCoste;
    }
    public int getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(int idVehiculo) {
        this.idVehiculo = idVehiculo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CostesDerivadosId) ) return false;
		 CostesDerivadosId castOther = ( CostesDerivadosId ) other; 
         
		 return (this.getIdTipoCoste()==castOther.getIdTipoCoste())
 && (this.getIdVehiculo()==castOther.getIdVehiculo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTipoCoste();
         result = 37 * result + this.getIdVehiculo();
         return result;
   }   


}


