package com.laguantera.dao;
// Generated 21-dic-2010 23:39:28 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Elementos generated by hbm2java
 */
public class Elementos  implements java.io.Serializable {


     private Integer idElemento;
     private TiposElemento tiposElemento;
     private String concepto;
     private Set opeEles = new HashSet(0);

    public Elementos() {
    }

	
    public Elementos(TiposElemento tiposElemento) {
        this.tiposElemento = tiposElemento;
    }
    public Elementos(TiposElemento tiposElemento, String concepto, Set opeEles) {
       this.tiposElemento = tiposElemento;
       this.concepto = concepto;
       this.opeEles = opeEles;
    }
   
    public Integer getIdElemento() {
        return this.idElemento;
    }
    
    public void setIdElemento(Integer idElemento) {
        this.idElemento = idElemento;
    }
    public TiposElemento getTiposElemento() {
        return this.tiposElemento;
    }
    
    public void setTiposElemento(TiposElemento tiposElemento) {
        this.tiposElemento = tiposElemento;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public Set getOpeEles() {
        return this.opeEles;
    }
    
    public void setOpeEles(Set opeEles) {
        this.opeEles = opeEles;
    }




}


