package com.laguantera.dao;
// Generated 21-dic-2010 23:39:28 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Galerias generated by hbm2java
 */
public class Galerias  implements java.io.Serializable {


     private Integer idGaleria;
     private Vehiculos vehiculos;
     private String titulo;
     private Set<Multimedias> multimediases = new HashSet(0);

    public Galerias() {
    }

	
    public Galerias(Vehiculos vehiculos) {
        this.vehiculos = vehiculos;
    }
    public Galerias(Vehiculos vehiculos, String titulo, Set multimediases) {
       this.vehiculos = vehiculos;
       this.titulo = titulo;
       this.multimediases = multimediases;
    }
   
    public Integer getIdGaleria() {
        return this.idGaleria;
    }
    
    public void setIdGaleria(Integer idGaleria) {
        this.idGaleria = idGaleria;
    }
    public Vehiculos getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Vehiculos vehiculos) {
        this.vehiculos = vehiculos;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Set<Multimedias> getMultimediases() {
        return this.multimediases;
    }
    
    public void setMultimediases(Set<Multimedias> multimediases) {
        this.multimediases = multimediases;
    }




}


