package com.laguantera.dao;
// Generated 21-dic-2010 23:39:28 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Marcas generated by hbm2java
 */
public class Marcas  implements java.io.Serializable {


     private Integer idMarca;
     private String nombreMarca;
     private Set modeloses = new HashSet(0);

    public Marcas() {
    }

    public Marcas(String nombreMarca, Set modeloses) {
       this.nombreMarca = nombreMarca;
       this.modeloses = modeloses;
    }
   
    public Integer getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(Integer idMarca) {
        this.idMarca = idMarca;
    }
    public String getNombreMarca() {
        return this.nombreMarca;
    }
    
    public void setNombreMarca(String nombreMarca) {
        this.nombreMarca = nombreMarca;
    }
    public Set getModeloses() {
        return this.modeloses;
    }
    
    public void setModeloses(Set modeloses) {
        this.modeloses = modeloses;
    }

    public void addModeloses(Modelos modelo){
        this.modeloses.add(modelo);
    }

}


