package com.laguantera.dao;
// Generated 21-dic-2010 23:39:28 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Modelos generated by hbm2java
 */
public class Modelos  implements java.io.Serializable {


     private Integer idModelo;
     private Marcas marcas;
     private String nombreModelo;
     private Set vehiculoses = new HashSet(0);
     private Set info_vehiculoses = new HashSet(0);

    public Modelos() {
    }

	
    public Modelos(Marcas marcas) {
        this.marcas = marcas;
    }
    public Modelos(Marcas marcas, String nombreModelo, Set vehiculoses) {
       this.marcas = marcas;
       this.nombreModelo = nombreModelo;
       this.vehiculoses = vehiculoses;
    }

    public Set getInfo_vehiculoses() {        
        return info_vehiculoses;
    }

    public void setInfo_vehiculoses(Set info_vehiculoses) {
        this.info_vehiculoses = info_vehiculoses;
    }
    
    public void addInfoVehiculoses(Info_Vehiculos info){
        this.info_vehiculoses.add(info);
    }
       
    public Integer getIdModelo() {
        return this.idModelo;
    }
    
    public void setIdModelo(Integer idModelo) {
        this.idModelo = idModelo;
    }
    public Marcas getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Marcas marcas) {
        this.marcas = marcas;
    }
    public String getNombreModelo() {
        return this.nombreModelo;
    }
    
    public void setNombreModelo(String nombreModelo) {
        this.nombreModelo = nombreModelo;
    }
    public Set getVehiculoses() {
        return this.vehiculoses;
    }
    
    public void setVehiculoses(Set vehiculoses) {
        this.vehiculoses = vehiculoses;
    }




}


