package com.laguantera.dao;
// Generated 21-dic-2010 23:39:28 by Hibernate Tools 3.2.1.GA



/**
 * Multimedias generated by hbm2java
 */
public class Multimedias  implements java.io.Serializable {


     private Integer idMultimedia;
     private TiposMultimedia tiposMultimedia;
     private Galerias galerias;
     private String titulo;
     private String ruta;
     private String descripcion;

    public Multimedias() {
    }

	
    public Multimedias(TiposMultimedia tiposMultimedia, Galerias galerias) {
        this.tiposMultimedia = tiposMultimedia;
        this.galerias = galerias;
    }
    public Multimedias(TiposMultimedia tiposMultimedia, Galerias galerias, String titulo, String ruta, String descripcion) {
       this.tiposMultimedia = tiposMultimedia;
       this.galerias = galerias;
       this.titulo = titulo;
       this.ruta = ruta;
       this.descripcion = descripcion;
    }
   
    public Integer getIdMultimedia() {
        return this.idMultimedia;
    }
    
    public void setIdMultimedia(Integer idMultimedia) {
        this.idMultimedia = idMultimedia;
    }
    public TiposMultimedia getTiposMultimedia() {
        return this.tiposMultimedia;
    }
    
    public void setTiposMultimedia(TiposMultimedia tiposMultimedia) {
        this.tiposMultimedia = tiposMultimedia;
    }
    public Galerias getGalerias() {
        return this.galerias;
    }
    
    public void setGalerias(Galerias galerias) {
        this.galerias = galerias;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


