package com.laguantera.dao;
// Generated 21-dic-2010 23:39:28 by Hibernate Tools 3.2.1.GA



/**
 * OpeEle generated by hbm2java
 */
public class OpeEle  implements java.io.Serializable {


     private OpeEleId id;
     private Elementos elementos;
     private Operaciones operaciones;
     private Float precioUnidad;
     private Integer cantidad;

    public OpeEle() {
    }

	
    public OpeEle(OpeEleId id, Elementos elementos, Operaciones operaciones) {
        this.id = id;
        this.elementos = elementos;
        this.operaciones = operaciones;
    }
    public OpeEle(OpeEleId id, Elementos elementos, Operaciones operaciones, Float precioUnidad, Integer cantidad) {
       this.id = id;
       this.elementos = elementos;
       this.operaciones = operaciones;
       this.precioUnidad = precioUnidad;
       this.cantidad = cantidad;
    }
   
    public OpeEleId getId() {
        return this.id;
    }
    
    public void setId(OpeEleId id) {
        this.id = id;
    }
    public Elementos getElementos() {
        return this.elementos;
    }
    
    public void setElementos(Elementos elementos) {
        this.elementos = elementos;
    }
    public Operaciones getOperaciones() {
        return this.operaciones;
    }
    
    public void setOperaciones(Operaciones operaciones) {
        this.operaciones = operaciones;
    }
    public Float getPrecioUnidad() {
        return this.precioUnidad;
    }
    
    public void setPrecioUnidad(Float precioUnidad) {
        this.precioUnidad = precioUnidad;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


