package com.laguantera.dao;
// Generated 21-dic-2010 23:39:28 by Hibernate Tools 3.2.1.GA



/**
 * OpeEleId generated by hbm2java
 */
public class OpeEleId  implements java.io.Serializable {


     private int idOperacion;
     private int idElemento;

    public OpeEleId() {
    }

    public OpeEleId(int idOperacion, int idElemento) {
       this.idOperacion = idOperacion;
       this.idElemento = idElemento;
    }
   
    public int getIdOperacion() {
        return this.idOperacion;
    }
    
    public void setIdOperacion(int idOperacion) {
        this.idOperacion = idOperacion;
    }
    public int getIdElemento() {
        return this.idElemento;
    }
    
    public void setIdElemento(int idElemento) {
        this.idElemento = idElemento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OpeEleId) ) return false;
		 OpeEleId castOther = ( OpeEleId ) other; 
         
		 return (this.getIdOperacion()==castOther.getIdOperacion())
 && (this.getIdElemento()==castOther.getIdElemento());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdOperacion();
         result = 37 * result + this.getIdElemento();
         return result;
   }   


}


