package com.laguantera.dao;
// Generated 21-dic-2010 23:39:28 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Operaciones generated by hbm2java
 */
public class Operaciones  implements java.io.Serializable {


     private Integer idOperacion;
     private TiposOperacion tiposOperacion;
     private Vehiculos vehiculos;
     private Date fecha;
     private Float importeTotal;
     private Integer kmVehiculo;
     private String responsable;
     private String lugar;
     private Set opeEles = new HashSet(0);

    public Operaciones() {
    }

	
    public Operaciones(TiposOperacion tiposOperacion, Vehiculos vehiculos) {
        this.tiposOperacion = tiposOperacion;
        this.vehiculos = vehiculos;
    }
    public Operaciones(TiposOperacion tiposOperacion, Vehiculos vehiculos, Date fecha, Float importeTotal, Integer kmVehiculo, String responsable, String lugar, Set opeEles) {
       this.tiposOperacion = tiposOperacion;
       this.vehiculos = vehiculos;
       this.fecha = fecha;
       this.importeTotal = importeTotal;
       this.kmVehiculo = kmVehiculo;
       this.responsable = responsable;
       this.lugar = lugar;
       this.opeEles = opeEles;
    }
   
    public Integer getIdOperacion() {
        return this.idOperacion;
    }
    
    public void setIdOperacion(Integer idOperacion) {
        this.idOperacion = idOperacion;
    }
    public TiposOperacion getTiposOperacion() {
        return this.tiposOperacion;
    }
    
    public void setTiposOperacion(TiposOperacion tiposOperacion) {
        this.tiposOperacion = tiposOperacion;
    }
    public Vehiculos getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Vehiculos vehiculos) {
        this.vehiculos = vehiculos;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Float getImporteTotal() {
        return this.importeTotal;
    }
    
    public void setImporteTotal(Float importeTotal) {
        this.importeTotal = importeTotal;
    }
    public Integer getKmVehiculo() {
        return this.kmVehiculo;
    }
    
    public void setKmVehiculo(Integer kmVehiculo) {
        this.kmVehiculo = kmVehiculo;
    }
    public String getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Set getOpeEles() {
        return this.opeEles;
    }
    
    public void setOpeEles(Set opeEles) {
        this.opeEles = opeEles;
    }




}


