package com.laguantera.dao;
// Generated 21-dic-2010 23:39:28 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TiposUsuario generated by hbm2java
 */
public class TiposUsuario  implements java.io.Serializable {


     private Integer idTipoUsuario;
     private String nombre;
     private String descripcion;     
     private String permisos;
     private Set usuarioses = new HashSet(0);     

    public TiposUsuario() {
    }

    public TiposUsuario(String nombre, String descripcion,String permisos,Set usuarioses) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.usuarioses = usuarioses;
       this.permisos = permisos;
    }
   
    public Integer getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(Integer idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }

    public String getPermisos() {
        return permisos;
    }

    public void setPermisos(String permisos) {
        this.permisos = permisos;
    }




}


