package com.laguantera.dao;
// Generated 21-dic-2010 23:39:28 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TiposMultimedia generated by hbm2java
 */
public class TiposMultimedia  implements java.io.Serializable {


     private Integer idTipoMultimedia;
     private String nombre;
     private Set multimediases = new HashSet(0);

    public TiposMultimedia() {
    }

    public TiposMultimedia(String nombre, Set multimediases) {
       this.nombre = nombre;
       this.multimediases = multimediases;
    }
   
    public Integer getIdTipoMultimedia() {
        return this.idTipoMultimedia;
    }
    
    public void setIdTipoMultimedia(Integer idTipoMultimedia) {
        this.idTipoMultimedia = idTipoMultimedia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getMultimediases() {
        return this.multimediases;
    }
    
    public void setMultimediases(Set multimediases) {
        this.multimediases = multimediases;
    }




}


