package com.laguantera.dao;
// Generated 21-dic-2010 23:39:28 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TiposOperacion generated by hbm2java
 */
public class TiposOperacion  implements java.io.Serializable {


     private Integer idTipoOperacion;
     private String nombre;
     private String descripcion;
     private Set operacioneses = new HashSet(0);

    public TiposOperacion() {
    }

    public TiposOperacion(String nombre, String descripcion, Set operacioneses) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.operacioneses = operacioneses;
    }
   
    public Integer getIdTipoOperacion() {
        return this.idTipoOperacion;
    }
    
    public void setIdTipoOperacion(Integer idTipoOperacion) {
        this.idTipoOperacion = idTipoOperacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getOperacioneses() {
        return this.operacioneses;
    }
    
    public void setOperacioneses(Set operacioneses) {
        this.operacioneses = operacioneses;
    }




}


