package com.laguantera.dao;
// Generated 21-dic-2010 23:39:28 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TiposElemento generated by hbm2java
 */
public class TiposElemento  implements java.io.Serializable {


     private Integer idTipoElemento;
     private String nombre;
     private String descripcion;
     private Set elementoses = new HashSet(0);

    public TiposElemento() {
    }

    public TiposElemento(String nombre, String descripcion, Set elementoses) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.elementoses = elementoses;
    }
   
    public Integer getIdTipoElemento() {
        return this.idTipoElemento;
    }
    
    public void setIdTipoElemento(Integer idTipoElemento) {
        this.idTipoElemento = idTipoElemento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getElementoses() {
        return this.elementoses;
    }
    
    public void setElementoses(Set elementoses) {
        this.elementoses = elementoses;
    }




}


