package com.laguantera.dao;
// Generated 21-dic-2010 23:39:28 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TiposCoste generated by hbm2java
 */
public class TiposCoste  implements java.io.Serializable {


     private Integer idTipoCoste;
     private String nombre;
     private String descripcion;
     private Set costesDerivadoses = new HashSet(0);

    public TiposCoste() {
    }

    public TiposCoste(String nombre, String descripcion, Set costesDerivadoses) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.costesDerivadoses = costesDerivadoses;
    }
   
    public Integer getIdTipoCoste() {
        return this.idTipoCoste;
    }
    
    public void setIdTipoCoste(Integer idTipoCoste) {
        this.idTipoCoste = idTipoCoste;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCostesDerivadoses() {
        return this.costesDerivadoses;
    }
    
    public void setCostesDerivadoses(Set costesDerivadoses) {
        this.costesDerivadoses = costesDerivadoses;
    }




}


