package com.laguantera.dao;
// Generated 21-dic-2010 23:39:28 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TiposCombustible generated by hbm2java
 */
public class TiposCombustible  implements java.io.Serializable {


     private Integer idTipoCombustible;
     private String nombre;
     private Set vehiculoses = new HashSet(0);

    public TiposCombustible() {
    }

    public TiposCombustible(String nombre, Set vehiculoses) {
       this.nombre = nombre;
       this.vehiculoses = vehiculoses;
    }
   
    public Integer getIdTipoCombustible() {
        return this.idTipoCombustible;
    }
    
    public void setIdTipoCombustible(Integer idTipoCombustible) {
        this.idTipoCombustible = idTipoCombustible;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getVehiculoses() {
        return this.vehiculoses;
    }
    
    public void setVehiculoses(Set vehiculoses) {
        this.vehiculoses = vehiculoses;
    }




}


