package com.laguantera.dao;
// Generated 21-dic-2010 23:39:28 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idUsuario;
     private TiposUsuario tiposUsuario;
     private String alias;
     private String password;
     private Integer codigoPostal;
     private String email;
     private Set vehiculoses = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(TiposUsuario tiposUsuario, String alias, String password, String email) {
        this.tiposUsuario = tiposUsuario;
        this.alias = alias;
        this.password = password;
        this.email = email;
    }
    public Usuarios(TiposUsuario tiposUsuario, String alias, String password, Integer codigoPostal, String email, Set vehiculoses) {
       this.tiposUsuario = tiposUsuario;
       this.alias = alias;
       this.password = password;
       this.codigoPostal = codigoPostal;
       this.email = email;
       this.vehiculoses = vehiculoses;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public TiposUsuario getTiposUsuario() {
        return this.tiposUsuario;
    }
    
    public void setTiposUsuario(TiposUsuario tiposUsuario) {
        this.tiposUsuario = tiposUsuario;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(Integer codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getVehiculoses() {
        return this.vehiculoses;
    }
    
    public void setVehiculoses(Set vehiculoses) {
        this.vehiculoses = vehiculoses;
    }




}


