package com.laguantera.dao;
// Generated 21-dic-2010 23:39:28 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculos generated by hbm2java
 */
public class Vehiculos  implements java.io.Serializable {


     private Integer idVehiculo;
     private TiposCombustible tiposCombustible;
     private Modelos modelos;
     private Usuarios usuarios;
     private String motor;
     private Integer tara;
     private String neumaticos;
     private Integer asientos;
     private Integer cilindros;
     private Integer cilindrada;
     private float cv;
     private Float kw;
     private String matricula;
     private Date fechaMatriculacion;
     private Date fechaFabricacion;
     private String imagen;
     private Set galeriases = new HashSet(0);
     private Set costesDerivadoses = new HashSet(0);
     private Set operacioneses = new HashSet(0);

    public Vehiculos() {
    }

	
    public Vehiculos(TiposCombustible tiposCombustible, Modelos modelos, Usuarios usuarios, String motor, float cv) {
        this.tiposCombustible = tiposCombustible;
        this.modelos = modelos;
        this.usuarios = usuarios;
        this.motor = motor;
        this.cv = cv;
    }
    public Vehiculos(TiposCombustible tiposCombustible, Modelos modelos, Usuarios usuarios, String motor, Integer tara, String neumaticos, Integer asientos, Integer cilindros, Integer cilindrada, float cv, Float kw, String matricula, Date fechaMatriculacion, Date fechaFabricacion, String imagen, Set galeriases, Set costesDerivadoses, Set operacioneses) {
       this.tiposCombustible = tiposCombustible;
       this.modelos = modelos;
       this.usuarios = usuarios;
       this.motor = motor;
       this.tara = tara;
       this.neumaticos = neumaticos;
       this.asientos = asientos;
       this.cilindros = cilindros;
       this.cilindrada = cilindrada;
       this.cv = cv;
       this.kw = kw;
       this.matricula = matricula;
       this.fechaMatriculacion = fechaMatriculacion;
       this.fechaFabricacion = fechaFabricacion;
       this.imagen = imagen;
       this.galeriases = galeriases;
       this.costesDerivadoses = costesDerivadoses;
       this.operacioneses = operacioneses;
    }
   
    public Integer getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(Integer idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public TiposCombustible getTiposCombustible() {
        return this.tiposCombustible;
    }
    
    public void setTiposCombustible(TiposCombustible tiposCombustible) {
        this.tiposCombustible = tiposCombustible;
    }
    public Modelos getModelos() {
        return this.modelos;
    }
    
    public void setModelos(Modelos modelos) {
        this.modelos = modelos;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getMotor() {
        return this.motor;
    }
    
    public void setMotor(String motor) {
        this.motor = motor;
    }
    public Integer getTara() {
        return this.tara;
    }
    
    public void setTara(Integer tara) {
        this.tara = tara;
    }
    public String getNeumaticos() {
        return this.neumaticos;
    }
    
    public void setNeumaticos(String neumaticos) {
        this.neumaticos = neumaticos;
    }
    public Integer getAsientos() {
        return this.asientos;
    }
    
    public void setAsientos(Integer asientos) {
        this.asientos = asientos;
    }
    public Integer getCilindros() {
        return this.cilindros;
    }
    
    public void setCilindros(Integer cilindros) {
        this.cilindros = cilindros;
    }
    public Integer getCilindrada() {
        return this.cilindrada;
    }
    
    public void setCilindrada(Integer cilindrada) {
        this.cilindrada = cilindrada;
    }
    public float getCv() {
        return this.cv;
    }
    
    public void setCv(float cv) {
        this.cv = cv;
    }
    public Float getKw() {
        return this.kw;
    }
    
    public void setKw(Float kw) {
        this.kw = kw;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public Date getFechaMatriculacion() {
        return this.fechaMatriculacion;
    }
    
    public void setFechaMatriculacion(Date fechaMatriculacion) {
        this.fechaMatriculacion = fechaMatriculacion;
    }
    public Date getFechaFabricacion() {
        return this.fechaFabricacion;
    }
    
    public void setFechaFabricacion(Date fechaFabricacion) {
        this.fechaFabricacion = fechaFabricacion;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Set getGaleriases() {
        return this.galeriases;
    }
    
    public void setGaleriases(Set galeriases) {
        this.galeriases = galeriases;
    }
    public Set getCostesDerivadoses() {
        return this.costesDerivadoses;
    }
    
    public void setCostesDerivadoses(Set costesDerivadoses) {
        this.costesDerivadoses = costesDerivadoses;
    }
    public Set getOperacioneses() {
        return this.operacioneses;
    }
    
    public void setOperacioneses(Set operacioneses) {
        this.operacioneses = operacioneses;
    }




}


